from task import calc


def main():
    cases = [("1 + 1", 2),
            ("8/16", 0.5),
            ("3 -(-1)", 4),
            ("2 + -2", 0),
            ("10- 2- -5", 13),
            ("(((10)))", 10),
            ("3 * 5", 15),
            ("7 - 3 * 5", -8),
            ("-82 / 24 / 73 / -17 - -66 - 67 + -15 * -6", 89.0027531),
            ("-7 * -(6 / 3)", 14)]

    cases += [
        ("-(-35) - (-1 * 77 + (33)) - (98 - ((((-77 / -72)))) / 21)", -18.949074074074076),
        ("86 / -38 * 75 * 1 * -22 * 39 * -52 * 6",  -45437873.684210524),
        ("-(-18) + (85 + 73 / (16)) * (65 - -(((-(-73 - 47)))) + -15", 15243.625),
        ("-(39) * (44 / -93 / (14)) + (-54 + (((-(-29 + -34)))) * 14)", 829.3179723),
        ("(-96) - (3 - 97 * (46)) - (-84 + -(((-(53 + 18)))) / 29)", 4444.5517),
        ("-(62) - (-69 * -26 - -(25)) - (-82 * (((-(77 - -92)))) - 87)", -15652)
    ]

    passed = 0
    for case, expected in cases:
        try:
            result = calc(case)
            assert result == expected
        except AssertionError:
            print(f"Failed on {case}. Expected {expected}, got {result}.")
        else:
            passed += 1
            print(f"Passed {case}.")
    print(f"Passed {passed} of {len(cases)} cases.")

if __name__ == '__main__':
    main()